server:
  port: 9090

spring:
  application:
    name: Customer
  datasource:
    username: 'bereket'
    url: jdbc:postgresql://localhost:5432/fraud
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true